name: Selenium BDD CI/CD

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"   # Runs at 2 AM Mon-Fri
  workflow_dispatch:         # Manual trigger

jobs:
  test:
    name: Run Cucumber Tests on ${{ matrix.os }} with JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Cucumber Tests
        run: mvn clean test -Dcucumber.filter.tags="@Login"

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-${{ matrix.os }}-jdk${{ matrix.java }}
          path: |
            target/cucumber-reports/*.html
            target/cucumber-reports/*.json
            target/surefire-reports/*.xml
